/**
 * Merge resources/weaponlist.json, luclinweapons.json, popweapons.json into resources/weapons.json
 * with per-item expansion: pop > luclin > classic (weaponlist-only).
 * Run: node scripts/merge-weapons.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const res = path.join(root, 'resources');

function loadJson(name) {
  const p = path.join(res, name);
  const raw = fs.readFileSync(p, 'utf8');
  return JSON.parse(raw);
}

const wl = loadJson('weaponlist.json');
const lu = loadJson('luclinweapons.json');
const po = loadJson('popweapons.json');

const allIds = new Set([
  ...Object.keys(wl),
  ...Object.keys(lu),
  ...Object.keys(po),
]);

const out = {};
for (const id of allIds) {
  // Stats: later eras override (pop > luclin > classic). Same ids often appear in both
  // luclinweapons.json and popweapons.json with identical data; pop wins for fields.
  const raw = po[id] || lu[id] || wl[id];
  if (!raw || typeof raw !== 'object') continue;
  // Era: luclin catalogue membership wins over pop so Luclin BIS is not tagged pop-only
  // when the same row exists in both files. True PoP-only keys are only in popweapons.json.
  const expansion = lu[id] ? 'luclin' : po[id] ? 'pop' : 'classic';
  out[id] = { ...raw, expansion };
}

const outPath = path.join(res, 'weapons.json');
fs.writeFileSync(outPath, JSON.stringify(out));
console.log('Wrote', outPath, 'items:', Object.keys(out).length);

/** Same data as window globals so index.html can load via script tag when opened as file:// (fetch is CORS-blocked). */
let exclusions = { global: [], fromRank: [], fromSearch: [] };
try {
  exclusions = JSON.parse(fs.readFileSync(path.join(res, 'weapon_exclusions.json'), 'utf8'));
} catch (e) {
  console.warn('weapon_exclusions.json not read, using empty exclusions:', e.message);
}
const jsPath = path.join(res, 'weapons-data.js');
const jsBody =
  '/* Generated by scripts/merge-weapons.mjs — do not edit. Enables opening index.html via file:// without CORS. */\n' +
  'window.__DPS_WEAPONS_MERGED__=' +
  JSON.stringify(out) +
  ';\nwindow.__DPS_WEAPON_EXCLUSIONS__=' +
  JSON.stringify(exclusions) +
  ';\n';
fs.writeFileSync(jsPath, jsBody);
console.log('Wrote', jsPath);
