/**
 * Emit resources/procrates-data.js for file:// (fetch to JSON is CORS-blocked).
 * Run: node scripts/procrates-to-js.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const res = path.join(__dirname, '..', 'resources');
const jsonPath = path.join(res, 'procrates.json');
const outPath = path.join(res, 'procrates-data.js');

const raw = fs.readFileSync(jsonPath, 'utf8');
const data = JSON.parse(raw);
if (!data || typeof data !== 'object') {
  console.error('Expected procrates.json to be a JSON object');
  process.exit(1);
}
const js =
  '/* Generated by scripts/procrates-to-js.mjs — do not edit. Enables file:// without CORS. */\n' +
  'window.__DPS_PROCRATES__=' +
  JSON.stringify(data) +
  ';\n';
fs.writeFileSync(outPath, js);
console.log('Wrote', outPath);
